version: "3.9"
services:

  yggdrasil:
    image: ghcr.io/dkushche/yggdrasil_service:master
    container_name: yggdrasil_gateway_container
    restart: always
    cap_add:
      - NET_ADMIN
      - DAC_OVERRIDE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - type: bind
        source: ./storage/yggdrasil
        target: /mnt/storage
      - type: bind
        source: ./config/resolv.conf
        target: /etc/resolv.conf

  alfis:
    image: ghcr.io/dkushche/alfis_service:master
    container_name: alfis_resolver_container
    restart: always
    volumes:
      - type: bind
        source: ./storage/alfis
        target: /mnt/storage
    network_mode: service:yggdrasil

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox_interface
    entrypoint: firefox
    shm_size: '2gb'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISPLAY=${DISPLAY}
    volumes:
      - type: bind
        source: ./storage/firefox
        target: /config
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    network_mode: service:yggdrasil
    depends_on:
      - alfis
      - yggdrasil
