version: "3.9"
services:
  yggdrasil:
    build: yggdrasil
    image: yggdrasil_gateway_image
    container_name: yggdrasil_gateway_container
    restart: always
    cap_add:
      - NET_ADMIN
      - DAC_OVERRIDE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - type: bind
        source: ./storage
        target: /mnt/storage

  alfis:
    build: alfis
    image: alfis_resolver_image
    container_name: alfis_resolver_container
    restart: always
    volumes:
      - type: bind
        source: ./storage
        target: /mnt/storage

  firefox:
    image: jlesage/firefox:v1.18.0
    container_name: firefox_interface
    shm_size: '2gb'
    environment:
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
    ports:
      - "5800:5800"
    volumes:
      - type: bind
        source: ./storage/firefox
        target: /config
