origin = "0000001D2A77D63477172678502E51DE7F346061FF7EB188A2445ECA3FC0780E"
check_blocks = 8

[net]
peers = ["peer-v4.alfis.name:4244", "peer-v6.alfis.name:4244", "peer-ygg.alfis.name:4244"]
listen = "[::]:4244"
public = true
yggdrasil_only = false

[dns]
listen = "0.0.0.0:53"
threads = 10
forwarders = ["https://dns.adguard.com/dns-query"]
bootstraps = ["9.9.9.9:53", "94.140.14.14:53"]

[mining]
threads = 0
lower = true
