name: Main

on: [push]

jobs:
  main_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Analysing the code with PyLint
      run: pylint yggway
